### ISSUE TITLE
Why install superset twice

### ISSUE THREAD

**Issue by zhangjiajie023** [muicoder/superset#1]
first time: `pip3 install superset`
second time: `python3 setup.py install`
between them changed the default language, is for building chinese?

After `pip install superset`, and i changed language to chinese, just the strings managed by flask-appbuilder can be translated, the rest in `zh/message.po` still is english, anything wrong? need rebuild ?

**Comment by muicoder** [comment]
Installed twice in order to solve the dependency problem.
chinese language: https://github.com/muicoder/superset/blob/master/Dockerfile#L21

**Comment by zhangjiajie023** [comment]
@muicoder yeah, i know how to set language in `config.py`. My problem is: when i set to 'zh', just the items belong to `Security` can be translated (by flask-appbuilder), but other items `Sources` `Slices` `SQL Lab` etc won't be translated (by superset). Have you meet this issue or know what happened? tks.

**Comment by muicoder** [comment]
https://github.com/airbnb/superset/blob/master/superset/translations/zh/LC_MESSAGES/messages.po
